apiVersion: apps/v1
kind: Deployment
metadata:
  name: alarm-demo
  labels:
    app: alarm-demo    
  namespace: afsha-demo-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alarm-demo
  template:
    metadata:
      labels:
        app: alarm-demo
    spec:
      containers:
      - name: alarm-demo
        image: afsha2206/alarm-demo:2.0
        ports:
          - containerPort: 80
        volumeMounts:
          - name: logs
            mountPath: /var/log/alarm-demo
      volumes:
        - name: logs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: alarm-demo-service
  namespace: afsha-demo-ns
spec:
  type: NodePort
  selector:
    app: alarm-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30005