apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alarm-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/<YOUR_ORG>/alarm-capstone'
    targetRevision: HEAD
    path: 'helm-chart'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: alarm-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true